blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
     path('', views.index, name="index"),       
     path('signin_view', views.signin_request, name="signin_view"),
     path('signup_view', views.signup_request, name="signup_view"),
     path('signout_view', views.signout_request, name="signout_view"),  
     path('newpost', views.newpost, name="newpost"),   
     path('profit', views.profit, name="profit"),
     path('contact', views.contact, name="contact"),          
 ]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

blog/models.py
from time import timezone
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class mCreatepost(models.Model):
     title = models.CharField(max_length=200)
     discription = models.TextField()
     body = models.TextField()     
     def __str__(self):
          return f"{self.id}: {self.title} - {self.discription}"

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import mCreatepost


class fUserCreate(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'placeholder': 'Username',
            'required': ''
        })
        self.fields['password1'].widget.attrs.update({
            'placeholder': 'Password',
            'required': ''
        })
        self.fields['password2'].widget.attrs.update({
            'placeholder': 'Password',
            'required': ''
        })
        self.fields['first_name'].widget.attrs.update({
            'placeholder': 'First name',
            'required': ''
        })
        self.fields['last_name'].widget.attrs.update({
            'placeholder': 'Last name',
            'required': ''
        })
        self.fields['email'].widget.attrs.update({
            'placeholder': 'Email',
            'required': ''
        })

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name",
                  "email", "password1", "password2"]
class fCreatepost(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={"rows":2,"placeholder":"title"}))
    discription = forms.CharField(widget=forms.Textarea(attrs={"rows":3,"placeholder":"discripion"}))
    body = forms.CharField(widget=forms.Textarea(attrs={"rows":8,"placeholder":"body"}))
    class Meta:
        model = mCreatepost
        fields = "__all__"

    

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .models import mCreatepost
from .forms import fUserCreate, fCreatepost
from django.http import HttpResponseRedirect
from django.shortcuts import render
# Create your views here.


def index(request):
     getPost = mCreatepost.objects.all()
     return render(request, "pages/index.html", {
          "posts": getPost
     })

def newpost(request):
     if not request.user.is_authenticated:
          return HttpResponseRedirect(reverse("blog:signin_view"))
     if request.method == "POST":
          form = fCreatepost(request.POST)
          if form.is_valid():
               saveForm = mCreatepost(title = form.cleaned_data["title"], discription = form.cleaned_data["discription"], body = form.cleaned_data["body"])
               saveForm.save()
               return render(request, "pages/newpost.html", {
                    "form": fCreatepost()
               })
          else:
               return render(request, "pages/newpost.html", {
                    "form": form
               })
     return render(request, "pages/newpost.html", {
          "form": fCreatepost()
     })

def profit(request):
     if not request.user.is_authenticated:
          return HttpResponseRedirect(reverse("blog:signin_view"))
     return render(request, "pages/profit.html")

def contact(request):
     return render(request, "pages/contact.html")

def signin_request(request):
     if request.method == "POST":
          username = request.POST["username"]
          password = request.POST["password"]
          user = authenticate(request, username=username, password=password)
          if user is not None:
               login(request, user)
               return HttpResponseRedirect(reverse("blog:index"))
          else:
               return render(request, "pages/signin.html", {
                    "message": "The username or password is incorrect!"
               })
     return render(request, "pages/signin.html")

def signup_request(request):
     if request.method == "POST":
          form = fUserCreate(request.POST)
          if form.is_valid():
               username = form.cleaned_data["username"]
               password = form.cleaned_data["password1"]
               form.save()
               new_user = authenticate(username=username, password=password)
               if new_user is not None:
                    login(request, new_user)
                    return HttpResponseRedirect(reverse("blog:index"))
               else:
                    return render(request, "pages/signup.html", {
                         "form": form
                    })
          else:
               return render(request, "pages/signup.html", {
                    "form": form

               })
     return render(request, "pages/signup.html", {
          "form": fUserCreate()
     })
def signout_request(request):
     logout(request)
     return HttpResponseRedirect(reverse("blog:index"))
 

blog/templates/pages/contact.html
{% extends 'pages/layout.html' %}

blog/templates/pages/index.html
{% extends 'pages/layout.html' %}
{% block container %}
<div class="content">
     <ul class="post-content">
          {% for post in posts %}
          <div class="post">
               <span class="item title"><li>{{ post.title }}</li></span>
               <span class="item discription"><li>{{ post.discription }}</li></span>
               <span class="item body"><li>{{ post.body }}</li></span>
          </div>
               {% endfor %}
     </ul>
</div>
{% endblock %}

blog/templates/pages/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" class="link-to-css">
  <link rel="stylesheet" href="{% static 'icon/css/all.css' %}">
  <link rel="stylesheet" href="{% static 'js/script.js' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My blog | Ẩn Danh</title>
</head>

<body>
  <div class="header">
    {% block header %}
    <div class="nav">
      <a href="#" class="logo">
        <img src="logo" alt="" class="logo-image" />
      </a>
      <ul class="menu">
        <li class="menu-item">
          <a href="{% url 'blog:index' %}" class="menu-link">Home</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'blog:newpost' %}" class="menu-link">New Post</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'blog:profit' %}" class="menu-link">Profile</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'blog:contact' %}" class="menu-link">Contact Us</a>
        </li>
      </ul>
      <div class="left-heading">
        <ul>
          <li><a href="#" class="fas fa-search"></a></li>
          <li><a href="#" class="fas fa-shopping-cart"></a></li>
          <li>
            <a href="#" class="user-icon fas fa-user"></a>
            <ul class="user-items">
              <li><a href="{% url 'blog:signin_view' %}">Sign In</a></li>
              <li><a href="{% url 'blog:signup_view' %}">Sign Up</a></li>
              <li><a href="{% url 'blog:signout_view' %}">Sign Out</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  {% endblock %}
  </div>
  <div class="container">
    {% block container %}
    {% endblock %}
  </div>
  {% block footer %}
  {% endblock %}
</body>
<script src="{% static 'js/script.js' %}"></script>

</html>

blog/templates/pages/newpost.html
{% extends 'pages/layout.html' %}
{% block container %}
<form action="{% url 'blog:newpost' %}" method="POST" class="fSignin">
     {% csrf_token %}
     <div class="model">
          <div class="heading">
               <h1 class="title">Create Your Post</h1>
          </div>
          {{ message }}
          <span>{{form.title}}</span>
          <span>{{form.discription}}</span>
          <span>{{form.body}}</span>
          <span><input type="submit" value="create" name="create"></span>
     </div>
</form>
{% endblock %}

blog/templates/pages/profit.html
{% extends 'pages/layout.html' %}
{% block container %}
     <ul>
          <li>{{request.user.username}}</li>
          <li>{{request.user.first_name}}</li>
          <li>{{request.user.email}}</li>
     </ul>
{% endblock %}

blog/templates/pages/signin.html
{% extends 'pages/layout.html' %}
{% block container %}
{% block title %}
{% endblock %}
<form action="{% url 'blog:signin_view' %}" method="POST" class="fSignin">
     {% csrf_token %}
     <div class="model">
          <div class="heading">
               <h1 class="title">Sign In To Access</h1>
          </div>
          {{ message }}
          <span><input type="text" name="username" placeholder="Username"></span>
          <span><input type="password" name="password" placeholder="Password"></span>
          <span><input type="submit" value="Sign In" name="signin"></span>
          <span><a href="{% url 'blog:signup_view' %}">Create new an account!</a></span>
     </div>
</form>
{% endblock %}

blog/templates/pages/signup.html
{% extends 'pages/layout.html' %}
{% block container %}
{% block title %}
{% endblock %}
<form action="{% url 'blog:signup_view' %}" method="POST" class="fSignin">
     {% csrf_token %}
     <div class="model">
          <div class="heading">
               <h1 class="title">Sign Up To Access</h1>
          </div>
          {{ message }}
          <span>{{form.username}}
          </span>
          <span>{{form.password1}}</span>
          <span>{{form.password2}}</span>
          <span>{{form.first_name}}</span>
          <span>{{form.last_name}}</span>
          <span>{{form.email}}</span>
          <span><input type="submit" value="Sign Up" name="signup"></span>
          <span><a href="{% url 'blog:signin_view' %}">Have had an account!</a></span>
     </div>
</form>
{% endblock %}